Don't lowercase name before titlizing to generate label
frctl/fractal pull request #1081
Opened 2021-09-24 20:24 UTC by khamer

This is a minor change that, when generating labels for components, uses the original case version of `name` instead of the lowercased version. This means having component folder names like `someComponent/` correctly become `Some Component`, whereas without this change, it becomes `Somecomponent`.

2021-09-26 14:27 UTC, mihkeleidast requested changes
I'm not sure about this change at all. `name` is [documented](https://fractal.build/guide/components/configuration-reference.html#name) as such: "values must be all lowercase, and contain only alphanumeric characters with hyphens or underscores for word seperators". 

Is there a reason for using camelCase instead of kebab-case for naming files/folders?

2021-09-26 14:27 UTC, mihkeleidast commented on packages/core/src/mixins/entity.js
> +                this.label = config.label || this._label(name);
The [Doc class](https://github.com/frctl/fractal/blob/main/packages/fractal/src/api/docs/doc.js#L26) expects `_label` method be passed the config object, not name.

2021-09-27 13:17 UTC, khamer commented
Yes - the files themselves are also being referenced by the CMS (Craft) by slug, and those slugs need to be alphanumeric identifiers (no dashes.)

I will update doc.js too, I don't see anything in the Doc class's _label method that would require access to the whole config object.

Maybe a better question is - what does this hurt? I believe it just improves the the label generation, but doesn't change what files Fractal looks at, handles, etc.

2021-11-04 18:13 UTC, mihkeleidast approved these changes

2021-11-04 18:23 UTC, mihkeleidast commented
Thanks, looks good! I'll try to get this merged once GitHub Actions starts working properly again.

2021-11-04 20:15 UTC, mihkeleidast commented
@khamer I have no idea why GitHub doesn't allow me to run the workflows or merge main in to fix the out-of-dateness. Would you mind filing the PR again? Thanks.

2021-11-04 20:26 UTC, khamer commented
@mihkeleidast Sure, but if you'd like, check this one once more - I pulled all the subsequent upstream commits to my fork, so it might let you merge cleanly now. If not, I'll just make a new PR.

2021-11-04 20:31 UTC, mihkeleidast commented
Oh cool, the "Approve and Run" button appeared now!

2021-11-04 20:39 UTC, mihkeleidast commented
@khamer do you have any idea why the diff isn't clean? 🤔

2021-11-05 13:45 UTC, khamer commented
Hrm, I'm not, but reset my main branch to upstream and cherrypicked just my two commits and now the diff looks clean, and files changed on github shows the right two instead of twelve.

2021-11-06 09:26 UTC, mihkeleidast commented
Thanks, looks good now!

2021-11-06 09:26 UTC, merged