Issue 658 - Relative path links from notes accessible both from local server as deployed server
frctl/fractal pull request #659
Opened 2020-09-08 12:16 UTC by ccGabbles

Stripping off the extension from the matcher, so that if you call an URL with extension, this won't get passed through to the matcher and therefore will return the appropriate component.

2020-09-11 22:44 UTC, mihkeleidast commented
I think the actual bug is in mandelbrot [here](https://github.com/frctl/fractal/blob/main/packages/mandelbrot/views/partials/browser/panel-notes.nunj#L4) - the docs.renderString method should accept env as it's third parameter, not second, as seen [here](https://github.com/frctl/fractal/blob/main/packages/fractal/src/api/docs/source.js#L83). Pretty sure if that renderString call is changed to `frctl.docs.renderString(entity.notes, null, renderEnv)`, this bug will be squashed and nothing else will break. In other places where docs are rendered in mandelbrot, context is passed as `null` apparently - see [here](https://github.com/frctl/fractal/blob/main/packages/mandelbrot/views/pages/doc.nunj#L21) for example.

2020-09-11 22:46 UTC, mihkeleidast requested changes
Let's fix this from mandelbrot

2020-09-13 08:46 UTC, ccGabbles commented
Changed the code accordingly, indeed makes more sense to apply the change in the proposed spot. Verified the change in de repro project and works there, no regression issues found either. Thank you for thinking with me here! :)

2020-09-21 07:59 UTC, ccGabbles commented
@mihkeleidast, fixed as proposed, do you have time to take a look at it again? :)

2020-09-21 08:01 UTC, mihkeleidast commented
I'll try to take a look sometime this week, been busy with moving & that cuts into my time usually allocated for Fractal.

2020-09-29 14:24 UTC, mihkeleidast approved these changes

2020-09-29 14:25 UTC, merged

2020-09-29 14:25 UTC, mihkeleidast commented
Thanks! Sorry it took a bit long to review.