build: migrate mandelbrot bundling from gulp to webpack
frctl/fractal pull request #676
Opened 2020-10-22 19:36 UTC by mihkeleidast

Resolves #585.

2020-10-24 09:16 UTC, LeBenLeBen requested changes

2020-10-24 15:02 UTC, mihkeleidast commented on packages/mandelbrot/assets/scss/components/_frame.scss
> +        background-image: url("../../img/loader.svg");
shouldn't affect, the build output should remain the same - the change is only for webpack so it'll find the assets.

2020-10-24 15:02 UTC, mihkeleidast commented on packages/mandelbrot/assets/js/mandelbrot.js
> -import 'core-js/features/array/find';
I think I tested on IE11 and it was fine?

2020-10-24 15:33 UTC, LeBenLeBen commented on packages/mandelbrot/assets/js/mandelbrot.js
> -import 'core-js/features/array/find';
`Array.find` is only used in specific places such as the search, the error shows up only once you interact with such features.

![Screenshot_2020-10-24 Dashboard](https://user-images.githubusercontent.com/793344/97085661-12caa600-161f-11eb-9e09-21a2f5bb58b1.png)

2020-10-24 15:40 UTC, LeBenLeBen commented on packages/mandelbrot/assets/scss/components/_frame.scss
> +        background-image: url("../../img/loader.svg");
Yeah I actually check a bunch of projects I have that extend Mandelbrot by importing Sass partials directly but those have the assets copied over already so it shouldn’t be a problem.

2020-10-25 08:14 UTC, mihkeleidast commented on packages/mandelbrot/assets/js/components/preview.js
> +            handleSelector: '> [data-role="resize-handle"]',
Good find, thanks.

2020-10-25 08:43 UTC, mihkeleidast commented on packages/mandelbrot/webpack.config.js
> +                        presets: ['@babel/preset-env'],
Yup, using ES6 import/export resolves this.

2020-10-25 08:44 UTC, mihkeleidast commented on packages/mandelbrot/assets/js/mandelbrot.js
> -import 'core-js/features/array/find';
Good find, thought I tested this before removing but apparently missed it. Either way, letting Babel automatically polyfill things like this makes sense, so I did that.

2020-10-25 18:13 UTC, LeBenLeBen approved these changes

2020-10-25 18:27 UTC, merged