fix: skip nunjucks path filter, when path is not defined
frctl/fractal pull request #940
Opened 2021-03-23 13:29 UTC by thomasaull

Using nunjucks with the following `context.js`:

```js
module.exports = {
  context: {
    default: {
      source: '/videos/my-video.mp4',
      poster: null,
    },
  },
};
```
and doing this in the `.nunjucks` will throw an error on build, because the `path` parameter is undefined:
```
{% set default = objectAppend(default, 'poster', default.poster | path) %}
```
Is it reasonable to just skip the path filter when the path is not defined? This way we can avoid a lot of additional logic in our templates.

2021-03-23 14:54 UTC, mihkeleidast commented
I'm personally more of a "don't call a function if required params are missing" guy instead of doing early returns in functions. But it might be safe to do this in a library setting, especially in this kind of templating, where there is no type checking other than getting runtime errors :)

2021-03-23 14:57 UTC, mihkeleidast requested changes
I would ask you to:
- add the same behavior to all the adapters (this is just as likely to come up with other templating engines)
- maybe add a integration test so this would be covered? "does not throw when path argument is missing" or something like that would be good.

2021-03-23 15:04 UTC, mihkeleidast commented
Note that #886 and #885 should probably be merged first to add tests...

2021-11-04 17:45 UTC, closed without merging

2021-11-04 17:55 UTC, thomasaull commented
@mihkeleidast Fair enough 😅